server:
  port: 8080

spring:
  application:
    name: msvc-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # CATEGORY SERVICE
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/category/**
          filters:
            - StripPrefix=1

        # DIFFICULTY SERVICE
        - id: difficulty-service
          uri: lb://DIFFICULTY-SERVICE
          predicates:
            - Path=/api/difficulty/**
          filters:
            - StripPrefix=1

        # QUIZ SERVICE
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/quiz/**
          filters:
            - StripPrefix=1

        # GAME SERVICE
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/api/game/**
          filters:
            - StripPrefix=1



eureka:
  cliente:
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
        